var searchData=
[
  ['begin',['begin',['../group__mainc.html#gac6e8e0e4c603c1bbfc0c7db3a58919f0',1,'nanodbc']]],
  ['bind',['bind',['../group__binding.html#gabe1b3e2f93e5b854f6f6a3dfa3250f5c',1,'nanodbc::statement::bind(short param_index, T const *value, param_direction direction=PARAM_IN)'],['../group__bind__multi.html#ga21de5d66a3e381040ca03a4f0fdcc5db',1,'nanodbc::statement::bind(short param_index, T const *values, std::size_t batch_size, param_direction direction=PARAM_IN)'],['../group__bind__multi.html#gadc594c1e061661b7f95639fcf25ec2cb',1,'nanodbc::statement::bind(short param_index, T const *values, std::size_t batch_size, T const *null_sentry, param_direction direction=PARAM_IN)'],['../group__bind__multi.html#gab7047fdb7cfec9bed6861b9a9c9b98cb',1,'nanodbc::statement::bind(short param_index, T const *values, std::size_t batch_size, bool const *nulls, param_direction direction=PARAM_IN)'],['../group__bind__multi.html#gac04830aadf2e00d3a3d05af8690eb241',1,'nanodbc::statement::bind(short param_index, std::vector&lt; std::vector&lt; uint8_t &gt;&gt; const &amp;values, param_direction direction=PARAM_IN)'],['../group__bind__multi.html#ga5242c1154450bfe699b73a2f26294560',1,'nanodbc::statement::bind(short param_index, std::vector&lt; std::vector&lt; uint8_t &gt;&gt; const &amp;values, bool const *nulls, param_direction direction=PARAM_IN)'],['../group__bind__multi.html#ga72e3b3fea37e2e8456f4cf2b66aa21f2',1,'nanodbc::statement::bind(short param_index, std::vector&lt; std::vector&lt; uint8_t &gt;&gt; const &amp;values, uint8_t const *null_sentry, param_direction direction=PARAM_IN)']]],
  ['binding_20multiple_20non_2dstring_20values',['Binding multiple non-string values',['../group__bind__multi.html',1,'']]],
  ['bind_5fnull',['bind_null',['../group__binding.html#ga1c92f0059d16d859355f61a020e78d13',1,'nanodbc::statement']]],
  ['bind_5fstrings',['bind_strings',['../group__bind__strings.html#ga1fc7e49ca9b8560e0ff122d78d3c9aff',1,'nanodbc::statement::bind_strings(short param_index, string::value_type const *values, std::size_t value_size, std::size_t batch_size, param_direction direction=PARAM_IN)'],['../group__bind__strings.html#ga0fe0be81be08cf7b847601fc8031f8fc',1,'nanodbc::statement::bind_strings(short param_index, std::vector&lt; string &gt; const &amp;values, param_direction direction=PARAM_IN)'],['../group__bind__strings.html#gaefd258ea836d002e32ef89facdfdc01a',1,'nanodbc::statement::bind_strings(short param_index, string::value_type const (&amp;values)[BatchSize][ValueSize], param_direction direction=PARAM_IN)'],['../group__bind__strings.html#ga6146ef352e2e714c36007f7739e29e7b',1,'nanodbc::statement::bind_strings(short param_index, string::value_type const *values, std::size_t value_size, std::size_t batch_size, string::value_type const *null_sentry, param_direction direction=PARAM_IN)'],['../group__bind__strings.html#gac85c4952672fdc334898e4043d7595dd',1,'nanodbc::statement::bind_strings(short param_index, std::vector&lt; string &gt; const &amp;values, string::value_type const *null_sentry, param_direction direction=PARAM_IN)'],['../group__bind__strings.html#gac6c325999b1418f7107a18c766c3381c',1,'nanodbc::statement::bind_strings(short param_index, string::value_type const (&amp;values)[BatchSize][ValueSize], string::value_type const *null_sentry, param_direction direction=PARAM_IN)'],['../group__bind__strings.html#ga9e417cca041c0e0de51dbc3f96df152c',1,'nanodbc::statement::bind_strings(short param_index, string::value_type const *values, std::size_t value_size, std::size_t batch_size, bool const *nulls, param_direction direction=PARAM_IN)'],['../group__bind__strings.html#ga2bea8a6f0ea78bdf647471ba1a5e38b0',1,'nanodbc::statement::bind_strings(short param_index, std::vector&lt; string &gt; const &amp;values, bool const *nulls, param_direction direction=PARAM_IN)'],['../group__bind__strings.html#ga1ffae7d8b469e58b48405814d4cf296a',1,'nanodbc::statement::bind_strings(short param_index, string::value_type const (&amp;values)[BatchSize][ValueSize], bool const *nulls, param_direction direction=PARAM_IN)'],['../group__bind__strings.html',1,'(Global Namespace)']]],
  ['binding_20parameters',['Binding parameters',['../group__binding.html',1,'']]],
  ['buffer_5flength',['buffer_length',['../classnanodbc_1_1catalog_1_1columns.html#af1616d5e1f9616bf72e3881e068fd435',1,'nanodbc::catalog::columns']]]
];
