sudo: required

language: cpp

branches:
  only:
    - master
    - latest
    - release
    - coverity_scan

git:
  depth: 10

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9c376e047374d89cdeac
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always   # default: never
    on_cancel: always # default: always
    on_error: always # default: always

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "xxaxm6smYwflaSmHZrr+ztEZj8SW47XniKZglyt26eFrVnvMWOHNIUoJqR59kV36vxX6Agi08mgVKKTrbrZOMzkFWFpNTwPU6eqyYY5UtMiMu4A9LrNfGyL0wPYgMtMVaCMCVDnIa4rh0bv69gheOc/0AwOA0xDfeHwwSvCE1voMK7iNvLcLIIex7QfNJQ2Mtp2w55VzIAoYc4FXPFB4LaBxMOk+VmleKAJxxvjLPBrhtmvcETnwq2dSmAxy8xLZ7OY7Z0bKrmFgQfjmvN1Q7cHBmKxmou0CKx00Ar++jURH18vyiRaN6+kKpLNkYhlbwYnOBM6/YPH79uo90vyNiYBkUfeJr2bBHP8RjEWBU0ZNNgBUm5DsefH6P/BSw02/nEM+wtn3Sfb2IOkHqqr4EfQDhcQMzFh893PqcJCQPbU/sGsCV/+Q/bxKpqOCu1X4jB6DW/ZJ4J5PlN+jpRfymZjG6pARW85eSrG2F3VdAhLsxT2dsDiPioZRshDJ59tPQdH5BTsmwf05c6oCXzzvcn8FHa29Nqo5Fe61QVzsazXgxnJe3KcengMBBdglI3T14SyrIWJAHzKZ/avS/LZ18seI/W8RQW16EyjEsOmK8QxGD0QHavpXLGn/68LJWIJOrwym6JKfxREttQ75gvZBVGU2zlEv77UirS6Zwl9/m1I="

ref:
  sources: &sources
    - boost-latest
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
  packages: &packages
    - cmake
    - cmake-data
    - g++-5
    - libboost-locale1.55-dev
    - libmyodbc
    - libsqliteodbc
    - mysql-client
    - odbc-postgresql
    - unixodbc
    - unixodbc-dev
  sqlite: &sqlite
    apt:
      sources: *sources
      packages: *packages
  mysql: &mysql
    mysql: "5.5"
    apt:
      sources: *sources
      packages: *packages
  postgresql: &postgresql
    postgresql: "9.1"
    apt:
      sources: *sources
      packages: *packages
  mariadb: &mariadb
    mariadb: "10.0"
    apt:
      sources: *sources
      packages: *packages
  vertica: &vertica
    apt:
      sources: *sources
      packages: *packages

matrix:
  include:
    - addons:
        apt:
          sources: *sources
          packages: *packages
        # The single build job that submits the Coverity Scan file
        coverity_scan:
          project:
            name: "lexicalunit/nanodbc"
            description: "A small C++ wrapper for ODBC"
          notification_email: mateusz@loskot.net
          build_command_prepend: mkdir -p build.coverity && pushd build.coverity && cmake -DCMAKE_BUILD_TYPE=Debug .. && popd
          build_command: cmake --build ./build.coverity
          branch_pattern: coverity_scan
      compiler: gcc
      env: DB=sqlite COVERITY=ON DISABLE_LIBCXX=ON DISABLE_EXAMPLES=OFF
      os: linux
    - addons: *sqlite
      compiler: gcc
      env: DB=sqlite BUILD_SHARED_LIBS=ON DISABLE_LIBCXX=ON
      os: linux
    - addons: *sqlite
      compiler: gcc
      env: DB=sqlite ENABLE_BOOST=ON DISABLE_LIBCXX=ON
      os: linux
    - addons: *mysql
      compiler: gcc
      env: DB=mysql DISABLE_LIBCXX=ON
      os: linux
    - addons: *mysql
      compiler: gcc
      env: DB=mysql ENABLE_BOOST=ON DISABLE_LIBCXX=ON
      os: linux
    - addons: *mysql
      compiler: gcc
      env: DB=mysql ENABLE_UNICODE=ON DISABLE_LIBCXX=ON DISABLE_EXAMPLES=OFF
      os: linux
    - addons: *mysql
      compiler: gcc
      env: DB=mysql ENABLE_UNICODE=ON ENABLE_BOOST=ON DISABLE_LIBCXX=ON DISABLE_EXAMPLES=OFF
      os: linux
    - addons: *postgresql
      compiler: gcc
      env: DB=postgresql DISABLE_LIBCXX=ON
      os: linux
    - addons: *mariadb
      compiler: gcc
      env: DB=mariadb DISABLE_LIBCXX=ON
      os: linux
    - addons: *vertica
      compiler: gcc
      env: DB=vertica DISABLE_LIBCXX=ON
      os: linux
    - compiler: clang
      env: DB=sqlite
      os: osx
    - compiler: clang
      env: DB=sqlite ENABLE_BOOST=ON
      os: osx
  allow_failures:
    - env: DB=mariadb DISABLE_LIBCXX=ON

# before_install runs after matrix.addons.apt installation targets in the matrix
before_install:
  - if [[ "$COVERITY" == "ON" ]]; then echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca- ; fi
  # Skip build if the commit message contains [skip travis] or [travis skip]
  # https://github.com/travis-ci/travis-ci/issues/5032
  - >
      echo "$TRAVIS_COMMIT_MESSAGE" | grep -E  '\[(skip travis|travis skip)\]'
      && echo "[skip travis] has been found, exiting."
      && exit 0 || true
  - ${TRAVIS_BUILD_DIR}/utility/ci/travis/before_install.$TRAVIS_OS_NAME.sh
  - ${TRAVIS_BUILD_DIR}/utility/ci/travis/before_install.vertica.sh

before_script:
  - source "${TRAVIS_BUILD_DIR}/utility/ci/travis/before_script.$DB.sh"
  - if [[ -f /etc/odbcinst.ini ]]; then export ODBCSYSINI=/etc; fi
  - if [[ -f /etc/odbc.ini ]]; then export ODBCINI=/etc/odbc.ini; fi
  - odbcinst -j
  - if [[ -f "$ODBCSYSINI/odbcinst.ini" ]]; then odbcinst -q -d; fi
  - if [[ -s "$ODBCINI" ]]; then odbcinst -q -s; fi

script:
  - ${TRAVIS_BUILD_DIR}/utility/ci/travis/script.sh
