# Ubuntu 24.04 is the newest release for which Microsoft publishes the SQL Server ODBC
# driver, and it packages the clang-format version .clang-format pins.
FROM ubuntu:24.04

ENV CXX="g++"
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get -qy update \
    && apt-get -qy install --no-upgrade --no-install-recommends \
    apt-transport-https \
    apt-utils \
    ca-certificates \
    ccache \
    clang \
    clang-format-20 \
    cmake \
    curl \
    g++ \
    git \
    gnupg \
    iputils-ping \
    libc++-dev \
    libc++abi-dev \
    libclang-rt-dev \
    libsqliteodbc \
    libssl-dev \
    llvm \
    locales \
    lsb-release \
    make \
    mysql-client \
    ninja-build \
    odbc-mariadb \
    odbc-postgresql \
    postgresql-client \
    sqlite3 \
    unixodbc \
    unixodbc-dev \
    vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# NOTE: To install ODBC 18 on Ubuntu, see: https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server
#       Keep in mind that only certain releases of Ubuntu are supported.
#       The .deb carries both the apt source and the key it is signed with, which the
#       source refers to by path.
RUN curl -sSL -o /tmp/packages-microsoft-prod.deb "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb" \
    && dpkg -i /tmp/packages-microsoft-prod.deb \
    && rm /tmp/packages-microsoft-prod.deb \
    && apt-get -qy update \
    && ACCEPT_EULA=Y apt-get -qy install --no-upgrade --no-install-recommends \
    msodbcsql18 \
    mssql-tools18 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && echo "export PATH=$PATH:/opt/mssql-tools18/bin" >> ~/.bash_profile \
    && echo "export PATH=$PATH:/opt/mssql-tools18/bin" >> ~/.bashrc \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
    && locale-gen \
    && odbcinst -i -d -f /usr/share/sqliteodbc/unixodbc.ini

# NOTE: To install mysql-connector-odbc on Ubuntu, see: https://dev.mysql.com/downloads/connector/odbc/
#       Keep in mind that only certain architectures are supported.
RUN curl -SL "https://downloads.mysql.com/archives/get/p/10/file/mysql-connector-odbc-8.4.0-linux-glibc2.28-$(uname -m).tar.gz" -o mysql-connector-odbc.tar.gz \
    && tar -xzf mysql-connector-odbc.tar.gz \
    && rm mysql-connector-odbc.tar.gz \
    && mv mysql-connector-odbc* /opt/mysql-connector-odbc \
    && /opt/mysql-connector-odbc/bin/myodbc-installer -d -a -n "MySQL ODBC 8.4 ANSI Driver" -t "DRIVER=/opt/mysql-connector-odbc/lib/libmyodbc8a.so;" \
    && /opt/mysql-connector-odbc/bin/myodbc-installer -d -a -n "MySQL ODBC 8.4 Unicode Driver" -t "DRIVER=/opt/mysql-connector-odbc/lib/libmyodbc8w.so;"

# docker-compose.yml mounts the working tree here.
WORKDIR /opt/nanodbc
