version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3.8.0-buster
    steps:
      - checkout
      - run:
          name: install markdownlint
          command: |
            curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g markdownlint-cli
            markdownlint --version
      - run:
          name: install rstcheck
          command: |
            sudo pip install rstcheck
            rstcheck --version
      - run:
          name: lint README.md
          command: markdownlint --config .markdownlint.json README.md
      - run:
          name: lint docs/
          command: |
            rstcheck -r doc
  build-deploy:
    docker:
      - image: circleci/python:3.8.0-buster
    steps:
      - checkout
      - run:
          name: install sphinx
          command: |
            sudo apt-get update -q
            sudo apt-get install -y python-sphinx doxygen
            sudo pip install sphinx_rtd_theme
            sudo pip install "breathe<=4.29.0"
      - run:
          name: generate docs
          command: |
            cd doc
            make html
      - run:
          name: deploy docs
          command: echo "TODO"

workflows:
  version: 2
  docs-workflow:
    jobs:
      - lint:
          filters:
            branches:
              only:
                - master
                - latest
                - release
      - build-deploy:
          requires:
            - lint
          filters:
            branches:
              only:
                - master
                - latest
                - release

notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/87eb42cf5644824442b1
