#!/usr/bin/env python3
#
# nanodbc documentation build configuration file, created by
# sphinx-quickstart on Tue Nov  1 22:27:39 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import re
import subprocess

# import sys
# sys.path.insert(0, os.path.abspath('.'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# requirements.txt pins nothing, so this is the floor the extensions themselves set:
# Furo requires Sphinx 6 or later.
needs_sphinx = "7.2"

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.githubpages",
]

doc_dir = os.path.dirname(os.path.realpath(__file__))

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The encoding of source files.
#
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "nanodbc"
copyright = "Amy Troschinetz and others."
author = "Amy Troschinetz"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# VERSION.txt is the one place the version is recorded, so that a release cannot ship
# documentation labelled with the version before it.
with open(os.path.join(os.path.dirname(doc_dir), "VERSION.txt")) as version_file:
    # The short X.Y version, and the full version including any alpha/beta/rc tag, are
    # the same for nanodbc: it releases only finished versions.
    version = release = version_file.read().strip()

# So that a page can name the version it documents without spelling it out, which is how
# the front page went on claiming to be v2.14.0 long after v2.15.0 was out.
rst_prolog = f"""
.. |release_tag| replace:: v{release}
"""

# Where the built pages are served from, which is also where each release keeps the
# archived copy of its own documentation.
site_url = "https://nanodbc.github.io/nanodbc"

# The generated fragment that versions.rst includes. It is written on every build rather
# than committed, so the list cannot fall behind what is actually published.
generated_dir = os.path.join(doc_dir, "_generated")
version_list_path = os.path.join(generated_dir, "versions.rst.inc")

# Stands in for the patch component of a series directory when ordering the list, a series
# being whatever patch was released from it most recently.
LATEST_IN_SERIES = float("inf")


def published_versions():
    """Versions whose documentation is on the website, newest first.

    The directories on the gh-pages branch are the only list that cannot name a version
    whose pages do not exist: several versions were tagged and released without their
    documentation ever being deployed. Returns None when the branch cannot be read, which
    is the normal case for a working copy that has never fetched it.
    """
    try:
        listing = subprocess.run(
            # --full-tree because ls-tree is otherwise relative to the directory it runs
            # in, and this one does not exist on the branch being listed.
            ["git", "ls-tree", "--full-tree", "--name-only", "origin/gh-pages"],
            cwd=doc_dir,
            capture_output=True,
            text=True,
            check=True,
        ).stdout
    except (OSError, subprocess.SubprocessError):
        return None

    # This build writes the root and the directory for its own minor series, so neither is
    # an older version: listing the series would have the page linking to itself. The full
    # version is excluded too, for the releases archived under one before the series
    # directories came in.
    series = ".".join(release.split(".")[:2])
    being_written = {f"v{release}", f"v{series}"}

    found = []
    for name in listing.split():
        # The patch component is optional: the series directories have none.
        matched = re.fullmatch(r"v(\d+)\.(\d+)(?:\.(\d+))?", name)
        if not matched or name in being_written:
            continue
        major, minor, patch = matched.groups()
        # A series directory carries the newest patch released from it, so it sorts above
        # any single release archived from the same minor.
        order = (int(major), int(minor), int(patch) if patch else LATEST_IN_SERIES)
        found.append((order, name))
    return [name for _, name in sorted(found, reverse=True)]


def write_version_list():
    versions = published_versions()
    if versions is None:
        body = (
            "The list of published versions is written from the website itself when the\n"
            "documentation is deployed. Fetch the ``gh-pages`` branch to build it here.\n"
        )
    elif not versions:
        body = "No other version has its documentation published yet.\n"
    else:
        body = "".join(f"- `{v} <{site_url}/{v}>`__\n" for v in versions)

    os.makedirs(generated_dir, exist_ok=True)
    with open(version_list_path, "w") as version_list:
        version_list.write(body)


def setup(app):
    write_version_list()

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#
# today = ''
#
# Else, today_fmt is used as the format for a strftime call.
#
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
# doc/README.md has the reader build in a virtualenv here, and its site-packages carry
# enough .rst of their own to bury the warnings that belong to nanodbc.
exclude_patterns = [".venv", ".pyvenv"]

# The reST default role (used for this markup: `text`) to use for all
# documents.
#
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
#
# The previous "sphinx" style paints its own background, a pale green that sits badly
# beside the API reference's fragments. These two are neutral, and _static/nanodbc.css
# paints the block itself with doxygen-awesome's fragment colour.
pygments_style = "friendly"
pygments_dark_style = "material"

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# Furo, rather than the theme this site used before, because it is the closest in
# structure to the doxygen-awesome-css theme the API reference uses -- one sidebar of
# navigation, one column of content -- and because it reads its colours and fonts from
# custom properties, which _static/nanodbc.css sets to doxygen-awesome's own values so
# that the two halves of the site match.
html_theme = "furo"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# doxygen-awesome-css's own custom properties, read out of its `html { ... }` block and
# the prefers-color-scheme block beneath it, at the tag doc/Makefile pins as
# AWESOME_VERSION. Mapping them onto the variables Furo reads is what makes these pages
# and the API reference beside them one site rather than two. Update both together.
#
# Furo writes these into a stylesheet of its own, at the selector and specificity its
# light/dark/auto switch expects. Setting them by hand in a plain stylesheet does not
# work, Furo declaring its own on `body` rather than `:root`.
_AWESOME_LIGHT = {
    "color-brand-primary": "#1779c4",  # --primary-color
    "color-brand-content": "#1779c4",
    "color-brand-visited": "#1779c4",
    "color-background-primary": "#ffffff",  # --page-background-color
    "color-background-secondary": "#fbfbfb",  # --side-nav-background
    "color-background-hover": "#f5f5f5",
    "color-background-border": "#dedede",  # --separator-color
    "color-foreground-primary": "#2f4153",  # --page-foreground-color
    "color-foreground-secondary": "#6f7e8e",  # --page-secondary-foreground-color
    "color-foreground-muted": "#6f7e8e",
    "color-foreground-border": "#dedede",
    "color-sidebar-background": "#fbfbfb",
    "color-sidebar-background-border": "#dedede",
    "color-sidebar-link-text--top-level": "#2f4153",
    "color-sidebar-brand-text": "#2f4153",
    "color-sidebar-search-border": "#dedede",
    "color-inline-code-background": "#f5f5f5",  # --code-background
    "color-api-background": "#f5f5f5",
    "color-admonition-background": "#e4f3ff",  # --note-color
    "color-card-border": "#dedede",
    "color-card-background": "#fbfbfb",
    "nanodbc-fragment-background": "#f8f9fa",  # --fragment-background
    "nanodbc-fragment-foreground": "#37474f",  # --fragment-foreground
}

_AWESOME_DARK = {
    "color-brand-primary": "#1982d2",
    "color-brand-content": "#1982d2",
    "color-brand-visited": "#1982d2",
    "color-background-primary": "#1c1d1f",
    "color-background-secondary": "#252628",
    "color-background-hover": "#2a2c2f",
    "color-background-border": "#38393b",
    "color-foreground-primary": "#d2dbde",
    "color-foreground-secondary": "#859399",
    "color-foreground-muted": "#859399",
    "color-foreground-border": "#38393b",
    "color-sidebar-background": "#252628",
    "color-sidebar-background-border": "#38393b",
    "color-sidebar-link-text--top-level": "#d2dbde",
    "color-sidebar-brand-text": "#d2dbde",
    "color-sidebar-search-border": "#38393b",
    "color-inline-code-background": "#2a2c2f",
    "color-api-background": "#2a2c2f",
    "color-admonition-background": "#163750",
    "color-card-border": "#38393b",
    "color-card-background": "#252628",
    "nanodbc-fragment-background": "#282c34",  # --fragment-background
    "nanodbc-fragment-foreground": "#dbe4eb",  # --fragment-foreground
}

html_theme_options = {
    "light_css_variables": _AWESOME_LIGHT,
    "dark_css_variables": _AWESOME_DARK,
    "source_repository": "https://github.com/nanodbc/nanodbc/",
    "source_branch": "main",
    "source_directory": "doc/",
}

# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = []

# The name for this set of Sphinx documents.
# "<project> v<release> documentation" by default.
#
# html_title = 'nanodbc vX.Y.Z'

# A shorter title for the navigation bar.  Default is the same as html_title.
#
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#
# html_logo = None

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#
# html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Loaded after the theme's own stylesheet, so that it can override the variables.
html_css_files = ["nanodbc.css"]

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#
# html_extra_path = []

# If not None, a 'Last updated on:' timestamp is inserted at every page
# bottom, using the given strftime format.
# The empty string is equivalent to '%b %d, %Y'.
#
# html_last_updated_fmt = None

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#
# html_additional_pages = {}

# If false, no module index is generated.
#
# html_domain_indices = True

# If false, no index is generated.
#
# html_use_index = True

# If true, the index is split into individual pages for each letter.
#
# html_split_index = False

# If true, links to the reST sources are added to the pages.
#
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'h', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'r', 'sv', 'tr', 'zh'
#
# html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# 'ja' uses this config value.
# 'zh' user can custom change `jieba` dictionary path.
#
# html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
#
# html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder.
htmlhelp_basename = "nanodbcdoc"

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, "nanodbc.tex", "nanodbc Documentation", "Amy", "manual"),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#
# latex_use_parts = False

# If true, show page references after internal links.
#
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
#
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
#
# latex_appendices = []

# It false, will not define \strong, \code, 	itleref, \crossref ... but only
# \sphinxstrong, ..., \sphinxtitleref, ... To help avoid clash with user added
# packages.
#
# latex_keep_old_macro_names = True

# If false, no module index is generated.
#
# latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "nanodbc", "nanodbc Documentation", [author], 1)]

# If true, show URL addresses after external links.
#
# man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "nanodbc",
        "nanodbc Documentation",
        author,
        "nanodbc",
        "A small C++ wrapper for the native C ODBC API.",
        "Miscellaneous",
    ),
]

# Documents to append as an appendix to all manuals.
#
# texinfo_appendices = []

# If false, no module index is generated.
#
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#
# texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#
# texinfo_no_detailmenu = False
