name: "Docs"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc/"
        pre-build-command: "apt-get update -y -q && apt-get install -y doxygen && pip install "breathe<=4.29.0"
