name: "documentation"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Install Doxygen
      run: sudo apt-get update -y && sudo apt-get install -y doxygen
    - name: Install Sphinx
      uses: actions/setup-python@v3
      run: pip install -r doc/requirements.txt
    - name: Build Documentation
      run: make html
      working-directory: ./doc
