---
# GHA workflow to build documentation and deploy with website in gh-pages branch
name: "Documentation"

on:
  push:
    branches:
      - main
      - gh-pages
    paths:
      - "doc/**"
      - "nanodbc/**"
  pull_request:
    paths:
      - "doc/**"
      - "nanodbc/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Install Doxygen
        run: sudo apt-get update -y && sudo apt-get install -y doxygen
      - name: Install Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      - name: Install Sphinx
        run: pip install -r doc/requirements.txt
      - name: Build Documentation
        run: make html
        working-directory: ./doc
