name: "Lint: docker"

on: [push, pull_request]

jobs:
  build:
    name: Dockerfile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hadolint/hadolint-action@v1.4.0
      with:
        dockerfile: Dockerfile
