name: "Lint: markdown"

on: [push, pull_request]

jobs:
  build:
    name: ".md"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: avto-dev/markdown-lint@v1
      with:
        args: '**/*.md'
