---
# GHA workflow to check well-formedness of sources, docs and auxiliary files
name: "Lint"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # source code format checked before builds by ci-{linux,windows}.yml

  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb # v1.5.0
        with:
          args: "**/*.md"
      - uses: docker://oskarstark/doctor-rst@sha256:6aa5162837be9d25505b2bcdd154bfe7352057503ce9de1b492b254c8e61a0e3 # 1.78.0
        with:
          args: --short --error-format=github
        env:
          DOCS_DIR: "doc/"

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: hadolint/hadolint-action@2a66e89f53d0771bb131a7fa31f3136336094aa6 # v3.4.0
        with:
          dockerfile: Dockerfile.dev
