name: Pages

on: [push, pull_request]
# on:
#   push:
#     branches:
#     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Install doxygen
      run: sudo apt-get update -y && sudo apt-get install -y doxygen
    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      with:
        documentation_path: ./doc/
        requirements_path: ./doc/requirements.txt
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
